namespace AkmlSql.Site.Telemetry;

using AkmlSql.Site.Analytics;

// Client error telemetry models: DTOs are the JSON wire shape posted by the desktop product
// (camelCase, web defaults); ClientErrorInfo/ClientErrorBatch are the store write shape carried
// through IAnalyticsSink; ClientErrorRow/ClientErrorsSummary are the read shapes for the
// /admin/errors page.

/// <summary>One error event in the posted batch. Bound from camelCase JSON with web defaults.</summary>
public sealed class ClientErrorEventDto
{
    /// <summary>When the error occurred on the client; the server receive time is used when absent/default.</summary>
    public DateTimeOffset Utc { get; set; }

    /// <summary>Serilog level name ("Error", "Warning", ...); anything unrecognised drops the event.</summary>
    public string? Level { get; set; }

    /// <summary>Human-readable error message.</summary>
    public string? Message { get; set; }

    /// <summary>Exception type/message/stack text.</summary>
    public string? Exception { get; set; }

    /// <summary>Originating component (e.g. "parser", "engine").</summary>
    public string? Source { get; set; }
}

/// <summary>The posted batch: one install's envelope plus its events.</summary>
public sealed class ClientErrorBatchDto
{
    /// <summary>Random GUID generated by the client on first run — never a machine or user id.</summary>
    public string? InstallId { get; set; }

    /// <summary>Product version string ("1.4.0").</summary>
    public string? ProductVersion { get; set; }

    /// <summary>Host process the product runs inside ("ssms", "VS").</summary>
    public string? Host { get; set; }

    /// <summary>
    /// Client OS description. Accepted for forward-compatibility but deliberately NOT stored —
    /// the schema has no column for it.
    /// </summary>
    public string? Os { get; set; }

    /// <summary>The error events; null/empty is a valid no-op batch (204, nothing recorded).</summary>
    public List<ClientErrorEventDto>? Events { get; set; }
}

/// <summary>
/// Normalises a client-reported level to the canonical Serilog casing. Anything outside the six
/// known names returns null, which the endpoint treats as "skip this event" — a level the
/// dashboard cannot group would corrupt the By-severity table.
/// </summary>
public static class ClientErrorLevelNormalization
{
    /// <summary>The canonical Serilog level names, least to most severe.</summary>
    public static readonly string[] Levels = ["Verbose", "Debug", "Information", "Warning", "Error", "Fatal"];

    /// <summary>Returns the canonical casing of a Serilog level name (case-insensitive), or null for anything else.</summary>
    public static string? Normalize(string? level)
    {
        if (string.IsNullOrWhiteSpace(level))
        {
            return null;
        }

        var trimmed = level.Trim();
        return Levels.FirstOrDefault(canonical => string.Equals(canonical, trimmed, StringComparison.OrdinalIgnoreCase));
    }
}

/// <summary>One validated, normalized client error ready for storage.</summary>
public sealed record ClientErrorInfo(
    DateTimeOffset ReceivedUtc,
    DateTimeOffset EventUtc,
    string Level,
    string Message,
    string? Exception,
    string? Source,
    string? ProductVersion,
    string? Host,
    string? InstallId);

/// <summary>The unit enqueued on <see cref="IAnalyticsSink"/> — one accepted POST's worth of errors.</summary>
public sealed record ClientErrorBatch(IReadOnlyList<ClientErrorInfo> Errors);

/// <summary>One stored error row as shown on /admin/errors.</summary>
public sealed record ClientErrorRow(
    long Id,
    DateTimeOffset Utc,
    string Level,
    string? ProductVersion,
    string? Host,
    string? InstallId,
    string Message,
    string? Exception);

/// <summary>
/// Read model for /admin/errors. Windows are rolling and inclusive of today, matching
/// <see cref="AnalyticsSummary"/>: "7d" = today plus the previous 6 days.
/// </summary>
public sealed class ClientErrorsSummary
{
    /// <summary>Requested window length in days.</summary>
    public required int Days { get; init; }

    /// <summary>All errors within the window, every level.</summary>
    public required long TotalWindow { get; init; }

    /// <summary>Errors per level within the window (level, count), descending by count.</summary>
    public required IReadOnlyList<CountRow> ByLevel { get; init; }

    /// <summary>Distinct non-empty install ids within the window.</summary>
    public required long DistinctInstallsWindow { get; init; }

    /// <summary>Latest stored rows in the window, newest first, optionally filtered to one level.</summary>
    public required IReadOnlyList<ClientErrorRow> Recent { get; init; }
}
