namespace AkmlSql.Site.Telemetry;

/// <summary>
/// Configuration binding for the <c>ClientErrors</c> section of appsettings.json.
/// <para>
/// This gates the receiver for ANONYMOUS client error reports posted by the desktop product.
/// Nothing IP-derived is ever read or stored; the only identity is <c>installId</c>, a random
/// GUID generated by the client on first run, which exists so "how many installs are hitting
/// this?" is answerable without knowing who anyone is.
/// </para>
/// </summary>
public sealed class ClientErrorOptions
{
    public const string SectionName = "ClientErrors";

    /// <summary>
    /// Master switch. When false the endpoint answers 404 — the feature is invisible, not
    /// merely disabled — and no data is accepted.
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Shared ingestion key. When set, a batch is accepted only if its
    /// <c>X-AKML-Ingest-Key</c> header matches (constant-time compare); anything else gets the
    /// same 404 as a disabled endpoint, so an unauthenticated caller cannot even tell the
    /// route exists. EMPTY in the repo — the live value is the <c>ClientErrors__IngestKey</c>
    /// environment variable on the app pool (same OPS pattern as <c>Admin__PasswordHash</c>),
    /// and the client posts the compile-time key embedded in the product. Leave empty only
    /// while old installs that predate the key must still report: empty means open intake.
    /// </summary>
    public string IngestKey { get; set; } = "";

    /// <summary>
    /// Maximum events accepted from one batch. Extra events are truncated (dropped), not
    /// rejected: a crashing client should never be told to retry with a smaller batch.
    /// </summary>
    public int MaxBatchEvents { get; set; } = 50;

    /// <summary>Stored error messages are truncated to this many characters.</summary>
    public int MaxMessageLength { get; set; } = 4000;

    /// <summary>Stored exception/stack text is truncated to this many characters.</summary>
    public int MaxExceptionLength { get; set; } = 8000;
}
