namespace AkmlSql.Site.Telemetry;

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using AkmlSql.Site.Analytics;

/// <summary>
/// Client error telemetry receiver: <c>POST /api/client-errors</c> accepts a batch of anonymous
/// error reports from the desktop product and enqueues ONE <see cref="ClientErrorBatch"/> for
/// background persistence.
/// <para>
/// Anonymous by design: the client IP is never read and <c>installId</c> is a random GUID
/// generated by the client — nothing on the wire identifies a person or a machine. Access is
/// gated by a shared ingestion key (the <see cref="IngestKeyHeader"/> header matched against
/// <see cref="ClientErrorOptions.IngestKey"/>) so the intake cannot be spammed or the dashboard
/// poisoned by strangers; while no key is configured the endpoint stays open so installs that
/// predate the key keep reporting. Transport is HTTPS-only at the site.
/// </para>
/// <para>
/// Validation problems (oversized body, malformed JSON, wrong shape) answer 400; a disabled
/// feature answers 404; an accepted batch — including an empty one, which is a no-op — answers
/// 204. Unexpected failures propagate to the pipeline's exception handler as a 500.
/// </para>
/// </summary>
public static class ClientErrorEndpoint
{
    /// <summary>Hard cap on the request body: an error batch is kilobytes, never megabytes.</summary>
    private const long MaxBodyBytes = 256 * 1024;

    /// <summary>Header that carries the shared ingestion key (matched against <see cref="ClientErrorOptions.IngestKey"/>).</summary>
    public const string IngestKeyHeader = "X-AKML-Ingest-Key";

    /// <summary>Envelope fields are capped independently of the message/exception text caps.</summary>
    private const int MaxEnvelopeFieldLength = 64;

    /// <summary>camelCase, case-insensitive — the JSON options ASP.NET uses for web payloads.</summary>
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    /// <summary>Registers the <c>/api/client-errors</c> route.</summary>
    public static void Map(IEndpointRouteBuilder endpoints) =>
        endpoints.MapPost("/api/client-errors", (
            HttpContext http,
            Microsoft.Extensions.Options.IOptions<ClientErrorOptions> options,
            IAnalyticsSink sink) => Handle(http, options.Value, sink));

    /// <summary>
    /// Handler body, factored out for tests: 404 when the feature is off, 400 for an oversized
    /// body or unparseable payload, 204 for an accepted batch (enqueued via
    /// <see cref="IAnalyticsSink.EnqueueClientErrors"/>, unless nothing survived validation).
    /// </summary>
    public static async Task<IResult> Handle(HttpContext http, ClientErrorOptions options, IAnalyticsSink sink)
    {
        if (!options.Enabled)
        {
            // Off means invisible: indistinguishable from a route that does not exist.
            return Results.NotFound();
        }

        if (!HasValidIngestKey(http, options))
        {
            // A missing/wrong key gets the same 404 as the disabled switch: an unauthenticated
            // caller learns nothing about the route, and the dashboard cannot be poisoned by
            // anyone who merely knows the URL.
            return Results.NotFound();
        }

        // Content-Length is the cheap pre-check; the capped read below is the real guard for
        // chunked requests that carry no length.
        if (http.Request.ContentLength is > MaxBodyBytes)
        {
            return Results.BadRequest();
        }

        var body = await ReadBodyWithCap(http);
        if (body is null)
        {
            return Results.BadRequest();
        }

        ClientErrorBatchDto? batch;
        try
        {
            batch = JsonSerializer.Deserialize<ClientErrorBatchDto>(body, JsonOptions);
        }
        catch (JsonException)
        {
            return Results.BadRequest();
        }

        if (batch is null)
        {
            // Well-formed JSON of the wrong shape ("null", a scalar, an array).
            return Results.BadRequest();
        }

        if (batch.Events is null or { Count: 0 })
        {
            // Nothing to do — a client with no new errors is not an error.
            return Results.NoContent();
        }

        var receivedUtc = DateTimeOffset.UtcNow;
        var installId = Cap(batch.InstallId, MaxEnvelopeFieldLength);
        var productVersion = Cap(batch.ProductVersion, MaxEnvelopeFieldLength);
        var host = Cap(batch.Host, MaxEnvelopeFieldLength);

        var errors = new List<ClientErrorInfo>(Math.Min(batch.Events.Count, Math.Max(options.MaxBatchEvents, 0)));
        foreach (var ev in batch.Events.Take(options.MaxBatchEvents))
        {
            var level = ClientErrorLevelNormalization.Normalize(ev.Level);
            if (level is null)
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(ev.Message) && string.IsNullOrWhiteSpace(ev.Exception))
            {
                continue;
            }

            var eventUtc = ev.Utc == default ? receivedUtc : ev.Utc;
            errors.Add(new ClientErrorInfo(
                receivedUtc,
                eventUtc,
                level,
                Cap(ev.Message, options.MaxMessageLength) ?? "",
                Cap(ev.Exception, options.MaxExceptionLength),
                Cap(ev.Source, MaxEnvelopeFieldLength),
                productVersion,
                host,
                installId));
        }

        if (errors.Count > 0)
        {
            sink.EnqueueClientErrors(new ClientErrorBatch(errors));
        }

        return Results.NoContent();
    }

    /// <summary>
    /// Ingestion-key gate. Open mode (no key configured) accepts everything so installs that
    /// predate the key keep reporting; once the server sets <c>ClientErrors__IngestKey</c>,
    /// only clients shipping the matching compile-time key get through. The compare is
    /// constant-time so the key cannot be probed byte-by-byte via response timing.
    /// </summary>
    private static bool HasValidIngestKey(HttpContext http, ClientErrorOptions options)
    {
        var expected = options.IngestKey;
        if (string.IsNullOrEmpty(expected))
        {
            return true;
        }

        var provided = http.Request.Headers[IngestKeyHeader].ToString();
        if (string.IsNullOrEmpty(provided))
        {
            return false;
        }

        var expectedBytes = Encoding.UTF8.GetBytes(expected);
        var providedBytes = Encoding.UTF8.GetBytes(provided);
        return expectedBytes.Length == providedBytes.Length
               && CryptographicOperations.FixedTimeEquals(expectedBytes, providedBytes);
    }

    /// <summary>Reads the request body, returning null the moment it exceeds <see cref="MaxBodyBytes"/>.</summary>
    private static async Task<byte[]?> ReadBodyWithCap(HttpContext http)
    {
        var buffer = new byte[MaxBodyBytes + 1];
        var total = 0;
        int read;
        while ((read = await http.Request.Body.ReadAsync(
                    buffer.AsMemory(total, buffer.Length - total), http.RequestAborted)) > 0)
        {
            total += read;
            if (total > MaxBodyBytes)
            {
                return null;
            }
        }

        return buffer.AsSpan(0, total).ToArray();
    }

    /// <summary>Truncates a client-supplied string to a cap; shorter values pass through untouched.</summary>
    private static string? Cap(string? value, int max) =>
        value is not null && value.Length > max ? value[..max] : value;
}
