using System.Diagnostics;
using AkmlSql.Core.Config;
using AkmlSql.Core.Ipc;
using AkmlSql.Core.Ipc.Messages;
using AkmlSql.Core.Models.Ai;
using AkmlSql.Engine.Ai;
using AkmlSql.Engine.Ai.Context;
using AkmlSql.Engine.Ai.Privacy;
using AkmlSql.Engine.Ai.Prompts;
using Microsoft.Extensions.AI;
using Serilog;

namespace AkmlSql.Engine.Handlers.Ai;

/// <summary>Spec 022 (M0 closure) -- P3 / US3. Concrete handler for <c>MessageTypes.AiFix</c>.
/// Suggests a corrected SQL statement given a failing SQL + error message. Replaces
/// <c>AiRequestHandler.HandleFixAsync</c>.</summary>
public sealed class AiFixHandler : AiHandlerBase<AiFixRequest, AiFixResponse>
{
    public AiFixHandler(AiPipelineServices svcs) : base(svcs) { }
    public override int RequestMessageType => MessageTypes.AiFix;
    public override int ResponseMessageType => MessageTypes.AiFixResult;

    protected override AiFixResponse BuildErrorResponse(string errorMessage, long elapsedMs) =>
        new() { Success = false, ErrorMessage = errorMessage, LatencyMs = (int)elapsedMs };

    protected override async Task<AiFixResponse> InvokeAsync(
        AiFixRequest request, RpcContext ctx, AiSettings settings, Stopwatch sw, CancellationToken ct)
    {
        if (!settings.Enabled) throw new InvalidOperationException("AI assistance is disabled");
        if (string.IsNullOrWhiteSpace(request.FailingSql)) throw new ArgumentException("No failing SQL provided");

        Log.Debug("AiFix: session={Session}, error={Error}, sql length={Length}",
            request.SessionId, request.ErrorMessage, request.FailingSql.Length);

        (string? ConnectionString, string? DatabaseName) sessionLookup(string sid)
        {
            var s = ctx.Sessions.GetSession(sid);
            return s == null || !s.IsConnected ? (null, null) : (s.ConnectionString, s.DatabaseName);
        }

        var schemaContext = await Services.SchemaContext.BuildAsync(
            request.SessionId, sessionLookup, request.FailingSql, compressionLevel: 3,
            maxObjects: settings.SchemaContextMaxObjects);
        var schemaText = SchemaContextFormatter.Format(schemaContext);
        var (transformedSql, transformedContext, transformation) =
            Services.Privacy.Transform(request.FailingSql, schemaContext, settings.PrivacyMode);
        if (transformedContext != null && transformation.IdentifierMap.Count > 0)
            schemaText = SchemaContextFormatter.Format(transformedContext);

        var (systemPrompt, userPrompt) = FixPrompt.Build(
            schemaText, transformedSql, request.ErrorMessage, request.ErrorNumber);

        var chatMessages = new List<ChatMessage>
        {
            new(ChatRole.System, systemPrompt),
            new(ChatRole.User, userPrompt),
        };
        var options = new ChatOptions { MaxOutputTokens = settings.MaxTokens, Temperature = (float)settings.Temperature };
        var (aiResponse, usedFallback) = await Services.ExecuteWithFallbackAsync(settings, chatMessages, options, ct);
        var responseText = aiResponse.Text ?? string.Empty;

        var fixedSql = AiPipelineServices.ExtractSection(responseText, "FIXED SQL:");
        var explanation = AiPipelineServices.ExtractSection(responseText, "EXPLANATION:");
        if (string.IsNullOrEmpty(fixedSql))
            (fixedSql, explanation) = AiPipelineServices.ParseFixSectionsFallback(responseText);

        if (transformation.IdentifierMap.Count > 0 || transformation.LiteralMap.Count > 0)
        {
            fixedSql = PrivacyTransformer.DeTransform(fixedSql, transformation);
            explanation = PrivacyTransformer.DeTransform(explanation, transformation);
        }
        fixedSql = AiPipelineServices.StripCodeFences(fixedSql);

        var annotations = AiPipelineServices.BuildDiffAnnotations(request.FailingSql, fixedSql);
        var validationAnnotations = Services.ValidateGeneratedSql(fixedSql, schemaContext);
        if (validationAnnotations.Count > 0) annotations.AddRange(validationAnnotations);

        if (usedFallback)
            explanation = $"[Note: Response generated by fallback model ({settings.OfflineProvider}/{settings.OfflineModel})]\n{explanation}";

        var tokensUsed = aiResponse.Usage != null
            ? (int)((aiResponse.Usage.InputTokenCount ?? 0) + (aiResponse.Usage.OutputTokenCount ?? 0)) : 0;
        sw.Stop();
        Log.Information("AiFix: success, tokens={Tokens}, latency={LatencyMs}ms, annotations={Count}, fallback={Fallback}",
            tokensUsed, sw.ElapsedMilliseconds, annotations.Count, usedFallback);

        return new AiFixResponse
        {
            Success = true, FixedSql = fixedSql, Explanation = explanation,
            Annotations = annotations, TokensUsed = tokensUsed,
            LatencyMs = (int)sw.ElapsedMilliseconds,
        };
    }
}
