using System.Diagnostics;
using AkmlSql.Core.Config;
using AkmlSql.Core.Ipc;
using AkmlSql.Core.Ipc.Messages;
using AkmlSql.Core.Models.Ai;
using AkmlSql.Engine.Ai;
using AkmlSql.Engine.Ai.Context;
using AkmlSql.Engine.Ai.Privacy;
using AkmlSql.Engine.Ai.Prompts;
using Microsoft.Extensions.AI;
using Serilog;

namespace AkmlSql.Engine.Handlers.Ai;

/// <summary>Spec 022 (M0 closure) -- P3 / US3. Concrete handler for <c>MessageTypes.AiIndexAnalysis</c>.
/// Analyses a SQL statement (+ optional execution plan) and suggests CREATE INDEX scripts.
/// Replaces <c>AiRequestHandler.HandleIndexAnalysisAsync</c>.</summary>
public sealed class AiIndexAnalysisHandler : AiHandlerBase<AiIndexAnalysisRequest, AiIndexAnalysisResponse>
{
    public AiIndexAnalysisHandler(AiPipelineServices svcs) : base(svcs) { }
    public override int RequestMessageType => MessageTypes.AiIndexAnalysis;
    public override int ResponseMessageType => MessageTypes.AiIndexAnalysisResult;

    protected override AiIndexAnalysisResponse BuildErrorResponse(string errorMessage, long elapsedMs) =>
        new() { Success = false, ErrorMessage = errorMessage, LatencyMs = (int)elapsedMs };

    protected override async Task<AiIndexAnalysisResponse> InvokeAsync(
        AiIndexAnalysisRequest request, RpcContext ctx, AiSettings settings, Stopwatch sw, CancellationToken ct)
    {
        if (!settings.Enabled) throw new InvalidOperationException("AI assistance is disabled");
        if (string.IsNullOrWhiteSpace(request.SelectedSql)) throw new ArgumentException("No SQL text provided");

        Log.Debug("AiIndexAnalysis: session={Session}, sql length={Length}, hasPlan={HasPlan}",
            request.SessionId, request.SelectedSql.Length, request.ExecutionPlanXml != null);

        (string? ConnectionString, string? DatabaseName) sessionLookup(string sid)
        {
            var s = ctx.Sessions.GetSession(sid);
            return s == null || !s.IsConnected ? (null, null) : (s.ConnectionString, s.DatabaseName);
        }

        var schemaContext = await Services.SchemaContext.BuildAsync(
            request.SessionId, sessionLookup, request.SelectedSql, compressionLevel: 3);
        var schemaText = SchemaContextFormatter.Format(schemaContext);
        var (transformedSql, transformedContext, transformation) =
            Services.Privacy.Transform(request.SelectedSql, schemaContext, settings.PrivacyMode);
        if (transformedContext != null && transformation.IdentifierMap.Count > 0)
            schemaText = SchemaContextFormatter.Format(transformedContext);

        string? transformedPlanXml = null;
        if (!string.IsNullOrWhiteSpace(request.ExecutionPlanXml))
        {
            if (transformation.IdentifierMap.Count > 0)
            {
                var planText = request.ExecutionPlanXml;
                foreach (var (original, hashed) in transformation.IdentifierMap.Select(kv => (kv.Value, kv.Key)))
                    planText = planText.Replace(original, hashed, StringComparison.OrdinalIgnoreCase);
                transformedPlanXml = planText;
            }
            else { transformedPlanXml = request.ExecutionPlanXml; }
        }

        var (systemPrompt, userPrompt) = IndexAnalysisPrompt.Build(schemaText, transformedSql, transformedPlanXml);
        var chatMessages = new List<ChatMessage>
        {
            new(ChatRole.System, systemPrompt),
            new(ChatRole.User, userPrompt),
        };
        var options = new ChatOptions { MaxOutputTokens = settings.MaxTokens, Temperature = (float)settings.Temperature };
        var (aiResponse, usedFallback) = await Services.ExecuteWithFallbackAsync(settings, chatMessages, options, ct);
        var responseText = aiResponse.Text ?? string.Empty;
        if (transformation.IdentifierMap.Count > 0 || transformation.LiteralMap.Count > 0)
            responseText = PrivacyTransformer.DeTransform(responseText, transformation);

        var summary = AiPipelineServices.ExtractSection(responseText, "SUMMARY:");
        var indexSuggestionsText = AiPipelineServices.ExtractSection(responseText, "INDEX SUGGESTIONS:");
        var suggestions = AiPipelineServices.ParseIndexSuggestions(indexSuggestionsText);

        if (usedFallback)
            summary = $"[Note: Response generated by fallback model ({settings.OfflineProvider}/{settings.OfflineModel})]\n{summary}";

        var tokensUsed = aiResponse.Usage != null
            ? (int)((aiResponse.Usage.InputTokenCount ?? 0) + (aiResponse.Usage.OutputTokenCount ?? 0)) : 0;
        sw.Stop();
        Log.Information("AiIndexAnalysis: success, tokens={Tokens}, latency={LatencyMs}ms, suggestions={Count}, fallback={Fallback}",
            tokensUsed, sw.ElapsedMilliseconds, suggestions.Count, usedFallback);

        return new AiIndexAnalysisResponse
        {
            Success = true, Suggestions = suggestions, Summary = summary,
            TokensUsed = tokensUsed, LatencyMs = (int)sw.ElapsedMilliseconds,
        };
    }
}
