using System.Diagnostics;
using AkmlSql.Core.Config;
using AkmlSql.Core.Ipc;
using AkmlSql.Core.Ipc.Messages;
using AkmlSql.Core.Models.Ai;
using AkmlSql.Engine.Ai;
using AkmlSql.Engine.Ai.Context;
using AkmlSql.Engine.Ai.Privacy;
using AkmlSql.Engine.Ai.Prompts;
using Microsoft.Extensions.AI;
using Serilog;

namespace AkmlSql.Engine.Handlers.Ai;

/// <summary>Spec 022 (M0 closure) -- P3 / US3. Concrete handler for <c>MessageTypes.AiOptimize</c>.
/// Suggests performance optimizations + index recommendations for a SQL statement. Replaces
/// <c>AiRequestHandler.HandleOptimizeAsync</c>.</summary>
public sealed class AiOptimizeHandler : AiHandlerBase<AiOptimizeRequest, AiOptimizeResponse>
{
    public AiOptimizeHandler(AiPipelineServices svcs) : base(svcs) { }
    public override int RequestMessageType => MessageTypes.AiOptimize;
    public override int ResponseMessageType => MessageTypes.AiOptimizeResult;

    protected override AiOptimizeResponse BuildErrorResponse(string errorMessage, long elapsedMs) =>
        new() { Success = false, ErrorMessage = errorMessage, LatencyMs = (int)elapsedMs };

    protected override async Task<AiOptimizeResponse> InvokeAsync(
        AiOptimizeRequest request, RpcContext ctx, AiSettings settings, Stopwatch sw, CancellationToken ct)
    {
        if (!settings.Enabled) throw new InvalidOperationException("AI assistance is disabled");
        if (string.IsNullOrWhiteSpace(request.SelectedSql)) throw new ArgumentException("No SQL text provided");

        Log.Debug("AiOptimize: session={Session}, sql length={Length}",
            request.SessionId, request.SelectedSql.Length);

        (string? ConnectionString, string? DatabaseName) sessionLookup(string sid)
        {
            var s = ctx.Sessions.GetSession(sid);
            return s == null || !s.IsConnected ? (null, null) : (s.ConnectionString, s.DatabaseName);
        }

        var schemaContext = await Services.SchemaContext.BuildAsync(
            request.SessionId, sessionLookup, request.SelectedSql, compressionLevel: 3);
        var schemaText = SchemaContextFormatter.Format(schemaContext);
        var (transformedSql, transformedContext, transformation) =
            Services.Privacy.Transform(request.SelectedSql, schemaContext, settings.PrivacyMode);
        if (transformedContext != null && transformation.IdentifierMap.Count > 0)
            schemaText = SchemaContextFormatter.Format(transformedContext);

        var (systemPrompt, userPrompt) = OptimizePrompt.Build(schemaText, transformedSql);
        var chatMessages = new List<ChatMessage>
        {
            new(ChatRole.System, systemPrompt),
            new(ChatRole.User, userPrompt),
        };
        var options = new ChatOptions { MaxOutputTokens = settings.MaxTokens, Temperature = (float)settings.Temperature };
        var (aiResponse, usedFallback) = await Services.ExecuteWithFallbackAsync(settings, chatMessages, options, ct);
        var responseText = aiResponse.Text ?? string.Empty;
        if (transformation.IdentifierMap.Count > 0 || transformation.LiteralMap.Count > 0)
            responseText = PrivacyTransformer.DeTransform(responseText, transformation);

        var optimizedSql = AiPipelineServices.ExtractSection(responseText, "OPTIMIZED SQL:");
        var explanation = AiPipelineServices.ExtractSection(responseText, "EXPLANATION:");
        var annotationsText = AiPipelineServices.ExtractSection(responseText, "ANNOTATIONS:");
        var indexSuggestionsText = AiPipelineServices.ExtractSection(responseText, "INDEX SUGGESTIONS:");
        optimizedSql = AiPipelineServices.StripCodeFences(optimizedSql);

        var annotations = AiPipelineServices.ParseAnnotations(annotationsText);
        var validationAnnotations = Services.ValidateGeneratedSql(optimizedSql, schemaContext);
        if (validationAnnotations.Count > 0) annotations.AddRange(validationAnnotations);
        var indexSuggestions = AiPipelineServices.ParseIndexSuggestions(indexSuggestionsText);

        if (usedFallback)
            explanation = $"[Note: Response generated by fallback model ({settings.OfflineProvider}/{settings.OfflineModel})]\n{explanation}";

        var tokensUsed = aiResponse.Usage != null
            ? (int)((aiResponse.Usage.InputTokenCount ?? 0) + (aiResponse.Usage.OutputTokenCount ?? 0)) : 0;
        sw.Stop();
        Log.Information("AiOptimize: success, tokens={Tokens}, latency={LatencyMs}ms, annotations={Annot}, indexes={Idx}, fallback={Fallback}",
            tokensUsed, sw.ElapsedMilliseconds, annotations.Count, indexSuggestions.Count, usedFallback);

        return new AiOptimizeResponse
        {
            Success = true, OptimizedSql = optimizedSql, Explanation = explanation,
            Annotations = annotations, IndexSuggestions = indexSuggestions,
            TokensUsed = tokensUsed, LatencyMs = (int)sw.ElapsedMilliseconds,
        };
    }
}
