using System.Diagnostics;
using AkmlSql.Core.Config;
using AkmlSql.Core.Ipc;
using AkmlSql.Core.Ipc.Messages;
using AkmlSql.Core.Models.Ai;
using AkmlSql.Engine.Ai;
using AkmlSql.Engine.Ai.Context;
using AkmlSql.Engine.Ai.Privacy;
using AkmlSql.Engine.Ai.Prompts;
using Microsoft.Extensions.AI;
using Serilog;

namespace AkmlSql.Engine.Handlers.Ai;

/// <summary>
/// Spec 022 (M0 closure) -- P3 / US3. Concrete handler for <c>MessageTypes.AiTextToSql</c>.
/// Translates a natural-language prompt + schema context into SQL via the configured AI provider.
/// Replaces <c>AiRequestHandler.HandleTextToSqlAsync</c>.
/// </summary>
public sealed class AiTextToSqlHandler : AiHandlerBase<AiTextToSqlRequest, AiTextToSqlResponse>
{
    public AiTextToSqlHandler(AiPipelineServices svcs) : base(svcs) { }
    public override int RequestMessageType => MessageTypes.AiTextToSql;
    public override int ResponseMessageType => MessageTypes.AiTextToSqlResult;
    public override AiFeature Feature => AiFeature.TextToSql;

    protected override AiTextToSqlResponse BuildErrorResponse(string errorMessage, long elapsedMs) =>
        new() { Success = false, ErrorMessage = errorMessage, LatencyMs = (int)elapsedMs };

    protected override async Task<AiTextToSqlResponse> InvokeAsync(
        AiTextToSqlRequest request, RpcContext ctx, AiSettings settings, AiAgent? resolvedAgent, Stopwatch sw, CancellationToken ct)
    {
        if (!settings.Enabled) throw new InvalidOperationException("AI assistance is disabled");
        if (string.IsNullOrWhiteSpace(request.Prompt)) throw new ArgumentException("Prompt cannot be empty");

        Log.Debug("AiTextToSql: session={Session}, prompt length={Length}",
            request.SessionId, request.Prompt.Length);

        (string? ConnectionString, string? DatabaseName) sessionLookup(string sid)
        {
            var s = ctx.Sessions.GetSession(sid);
            return s == null || !s.IsConnected ? (null, null) : (s.ConnectionString, s.DatabaseName);
        }

        var schemaContext = await Services.SchemaContext.BuildAsync(
            request.SessionId, sessionLookup, request.Prompt, compressionLevel: 3,
            maxObjects: settings.SchemaContextMaxObjects);
        var schemaText = SchemaContextFormatter.Format(schemaContext);
        var (transformedPrompt, transformedContext, transformation) =
            Services.Privacy.Transform(request.Prompt, schemaContext, settings.PrivacyMode);
        if (transformedContext != null && transformation.IdentifierMap.Count > 0)
            schemaText = SchemaContextFormatter.Format(transformedContext);
        var (systemPrompt, userPrompt) = TextToSqlPrompt.Build(schemaText, transformedPrompt);

        var chatMessages = new List<ChatMessage>
        {
            new(ChatRole.System, systemPrompt),
            new(ChatRole.User, userPrompt),
        };
        var options = new ChatOptions
        {
            MaxOutputTokens = settings.MaxTokens,
            Temperature = (float)settings.Temperature,
        };
        var (aiResponse, usedFallback, _) = await Services.ExecuteWithFallbackAsync(
            settings, resolvedAgent, chatMessages, options, ct);
        var generatedSql = aiResponse.Text ?? string.Empty;

        if (transformation.IdentifierMap.Count > 0 || transformation.LiteralMap.Count > 0)
            generatedSql = PrivacyTransformer.DeTransform(generatedSql, transformation);
        generatedSql = AiPipelineServices.StripCodeFences(generatedSql);
        var validationAnnotations = Services.ValidateGeneratedSql(generatedSql, schemaContext);

        var tokensUsed = aiResponse.Usage != null
            ? (int)((aiResponse.Usage.InputTokenCount ?? 0) + (aiResponse.Usage.OutputTokenCount ?? 0))
            : 0;
        sw.Stop();
        // Spec 037 (FR-052): non-chat fallback is recorded for diagnosis, not surfaced by
        // name — the engine log names who answered; the user-facing note stays generic.
        var notice = usedFallback
            ? "[Note: Response generated by a fallback provider]"
            : null;
        Log.Information("AiTextToSql: success, tokens={Tokens}, latency={LatencyMs}ms, fallback={Fallback}",
            tokensUsed, sw.ElapsedMilliseconds, usedFallback);

        return new AiTextToSqlResponse
        {
            Success = true,
            GeneratedSql = notice != null ? $"-- {notice}\n{generatedSql}" : generatedSql,
            TokensUsed = tokensUsed,
            LatencyMs = (int)sw.ElapsedMilliseconds,
            Annotations = validationAnnotations.Count > 0 ? validationAnnotations : null,
        };
    }
}
